services:
  - type: web
    name: ok-glacons-website
    env: node
    region: frankfurt
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

